---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[yum-epel]

      - recipe[qpid::server]
    attributes:
